application: kbtw-el6240
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:       # static then dynamic

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/bootstrap/css

- url: /fonts
  static_dir: static/fonts

- url: /partials
  static_dir: static/partials

- url: /
  static_files: templates/index.html
  upload: templates/index\.html
  secure: always
  
- url: /tasks/send_notifmail  
  script: main.app
  
- url: /crons/set_task 
  script: main.app  
  
- url: /tasks/cek_jatuhtempo 
  script: main.app  

- url: /_ah/spi/.*
  script: emailnotif.api
  secure: always
 
libraries:
- name: endpoints
  version: 1.0

